#define SECRET_PINNUMBER     "1234" // REPLACE  THIS WITH YOUR ACTUAL SIM PIN NUMBER
#define MOSQUITTO_CREDENTIALS_USERNAME    "User" // REPLACE  THIS WITH YOUR ACTUAL USERNAME
#define MOSQUITTO_CREDENTIALS_PASSWORD    "Password" // REPLACE  THIS WITH YOUR ACTUAL PASSWORD
#define SECRET_MQTT_SERVER "34.123.45.67" // REPLACE  THIS WITH YOUR ACTUAL GCP IP
