#define SECRET_PINNUMBER     "1234" // USER: REPLACE  THIS WITH YOUR ACTUAL SIM PIN NUMBER
#define MOSQUITTO_CREDENTIALS_USERNAME    "User"
#define MOSQUITTO_CREDENTIALS_PASSWORD    "Password"
#define SECRET_MQTT_SERVER "34.123.45.67" // Replace with your actual GCP IP
